jpa.default.properties.hibernate.hbm2ddl.auto = 'update'

[micronaut]
application.name = 'mircolight'
metrics.enabled = true

[datasources.default]
url = 'jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE'
username = 'sa'
password = ''
driver-class-name = 'org.h2.Driver'

[jpa.default.entity-scan]
packages = ['io.no767.mircolight.models']

[micronaut.router.static-resources.swagger]
paths = 'classpath:META-INF/swagger'
mapping = '/swagger/**'

[micronaut.router.static-resources.swagger-ui]
paths = 'classpath:META-INF/swagger/views/swagger-ui'
mapping = '/swagger-ui/**'

[micronaut.metrics.export.prometheus]
enabled = true
descriptions = true
step = 'PT1M'
